### PR TITLE
[WIP] Clear dependencies

### PR DESCRIPTION
**Pull request by konimex**
Working towards a complete chroot `kiss`-only system (currently I am building it in a Alpine chroot), I think we better clear dependencies between packages, add missing dependencies, and change deps to makedep or vice versa.

- [ ] autoconf
- [ ] automake
- [x] binutils
- [x] bison
- [x] busybox
- [x] ca-certificates
- [ ] cmake
- [x] flex
- [x] gettext
- [ ] git
**Missing**: `linux-headers`
- [x] gmp
- [ ] libelf
- [x] libffi
- [x] libressl
- [ ] linux
- [ ] llvm
- [x] m4
- [x] mpc1
- [x] mpfr
- [ ] musl
- [ ] patch
- [ ] perl
- [ ] pkgconf
- [ ] python
- [x] sharutils
- [x] zlib

Also, we're missing `gcc` to compile all these packages, we'll probably need to create `gcc` package first.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Almost finished with a `linux-headers` package. Also have a `gcc` package almost done.

**Comment by dylanaraps** [comment]
Lets move this to an issue and work in `master`. :+1:

**Comment by dylanaraps** [comment]
I've pushed a `linux-headers` and `gcc` package to master. Dependencies still need to be classified and `gcc` still needs to be built.

**Comment by konimex** [comment]
For some reason I can't push to `master`. Also, I'll close this PR in 5 minutes (or you can merge this PR).

**Comment by dylanaraps** [comment]
Will check the permissions.

**Pull request merged**
